#!/usr/bin/env python3
"""
PBIP AI Auditor
A comprehensive script to validate the integrity of Power BI Project (PBIP) files 
customized or generated by AI agents.

This auditor specifically targets the modern PBIR folder structure:
- .Report/definition/pages/pages.json
- .Report/definition/pages/<page_name>/page.json
- .Report/definition/pages/<page_name>/visuals/<visual_name>/visual.json

It checks for:
1. JSON parsing errors (malformed JSON generated by AI).
2. Schema adherence (missing required keys like $schema, name, position).
3. Logical integrity (pages listed in pages.json actually exist).
4. Layout sanity (visuals out of bounds or with negative dimensions).
"""

import sys
import json
from pathlib import Path

def validate_visual_json(visual_path: Path, page_name: str) -> list:
    issues = []
    try:
        with open(visual_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
            
        if "$schema" not in data:
            issues.append(f"Visual '{visual_path.name}' in page '{page_name}' is missing '$schema'.")
            
        if "name" not in data:
            issues.append(f"Visual '{visual_path.name}' in page '{page_name}' is missing 'name'.")
            
        pos = data.get("position", {})
        if not pos:
            issues.append(f"Visual '{visual_path.name}' in page '{page_name}' is missing 'position' payload.")
        else:
            x, y = pos.get('x', 0), pos.get('y', 0)
            w, h = pos.get('width', 0), pos.get('height', 0)
            
            if w <= 0 or h <= 0:
                issues.append(f"Visual '{visual_path.name}' in page '{page_name}' has invalid dimensions: W={w}, H={h}.")
            if x < 0 or y < 0:
                issues.append(f"Visual '{visual_path.name}' in page '{page_name}' is placed out of bounds: X={x}, Y={y}.")
                
        if "visual" not in data or "visualType" not in data.get("visual", {}):
            issues.append(f"Visual '{visual_path.name}' in page '{page_name}' is missing 'visual.visualType'.")
            
    except json.JSONDecodeError as e:
        issues.append(f"CRITICAL: Failed to parse '{visual_path}' as JSON. AI generated malformed JSON: {e}")
    except Exception as e:
        issues.append(f"Error checking '{visual_path}': {e}")
        
    return issues

def validate_page_json(page_path: Path) -> list:
    issues = []
    try:
        with open(page_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
            
        if "$schema" not in data:
            issues.append(f"Page '{page_path.parent.name}' is missing '$schema'.")
            
        if "name" not in data:
            issues.append(f"Page '{page_path.parent.name}' is missing 'name'.")
            
        if "displayName" not in data:
            issues.append(f"Page '{page_path.parent.name}' is missing 'displayName'.")
            
    except json.JSONDecodeError as e:
        issues.append(f"CRITICAL: Failed to parse '{page_path}' as JSON. AI generated malformed JSON: {e}")
    except Exception as e:
        issues.append(f"Error checking '{page_path}': {e}")
    
    return issues

def validate_pages_json(pages_json_path: Path, actual_page_folders: set) -> list:
    issues = []
    try:
        with open(pages_json_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
            
        page_order = data.get("pageOrder", [])
        if not page_order:
            issues.append(f"'{pages_json_path.name}' has empty or missing 'pageOrder'. Report will have no pages.")
            
        active_page = data.get("activePageName")
        if active_page and active_page not in page_order:
            issues.append(f"'{pages_json_path.name}' defines activePageName '{active_page}' which is not in 'pageOrder'.")
            
        # Check for discrepancies between pages.json and actual folders
        page_order_set = set(page_order)
        
        missing_folders = page_order_set - actual_page_folders
        if missing_folders:
            issues.append(f"pages.json lists pages that do not exist as folders: {missing_folders}")
            
        orphaned_folders = actual_page_folders - page_order_set
        if orphaned_folders:
            issues.append(f"Found page folders not listed in pages.json (they will not appear in the report): {orphaned_folders}")
            
    except json.JSONDecodeError as e:
        issues.append(f"CRITICAL: Failed to parse '{pages_json_path}' as JSON. {e}")
    except Exception as e:
        issues.append(f"Error checking '{pages_json_path}': {e}")
        
    return issues

def main():
    target_dir = Path(sys.argv[1] if len(sys.argv) > 1 else ".")
    print(f"\n🔍 PBIP AI Auditor running on: {target_dir}\n")
    
    report_dirs = list(target_dir.rglob("*.Report/definition/pages"))
    if not report_dirs:
        print("ℹ️ No '.Report/definition/pages' directory found. Are you running this in a PBIP project?")
        sys.exit(0)
        
    total_issues = 0
    
    for pages_dir in report_dirs:
        report_name = pages_dir.parent.parent.name
        print(f"📊 Analyzing Report: {report_name}")
        
        # 1. Gather actual page folders
        page_folders = [d for d in pages_dir.iterdir() if d.is_dir()]
        page_folder_names = {d.name for d in page_folders}
        
        # 2. Validate pages.json
        pages_json_path = pages_dir / "pages.json"
        if not pages_json_path.exists():
            print(f"   ❌ CRITICAL: Missing required file '{pages_json_path}'")
            total_issues += 1
        else:
            issues = validate_pages_json(pages_json_path, page_folder_names)
            for issue in issues:
                print(f"   ❌ {issue}")
                total_issues += 1
                
        # 3. Validate each page and its visuals
        for page_folder in page_folders:
            page_json_path = page_folder / "page.json"
            if not page_json_path.exists():
                print(f"   ❌ CRITICAL: Missing 'page.json' in page folder '{page_folder.name}'")
                total_issues += 1
            else:
                issues = validate_page_json(page_json_path)
                for issue in issues:
                    print(f"   ❌ {issue}")
                    total_issues += 1
                    
            # Check visuals
            visuals_dir = page_folder / "visuals"
            if visuals_dir.exists():
                for visual_folder in visuals_dir.iterdir():
                    if visual_folder.is_dir():
                        visual_json_path = visual_folder / "visual.json"
                        if not visual_json_path.exists():
                            print(f"   ❌ CRITICAL: Missing 'visual.json' in visual folder '{page_folder.name}/visuals/{visual_folder.name}'")
                            total_issues += 1
                        else:
                            issues = validate_visual_json(visual_json_path, page_folder.name)
                            for issue in issues:
                                print(f"   ❌ {issue}")
                                total_issues += 1


    print("\n" + "="*50)
    if total_issues == 0:
        print("✅ ALL CHECKS PASSED: The AI-generated PBIP JSON structure is fully valid!")
        sys.exit(0)
    else:
        print(f"⚠️ AUDIT FAILED: Found {total_issues} integrity issues in the PBIP files.")
        print("   Please instruct the AI to fix these problems.")
        sys.exit(1)

if __name__ == "__main__":
    main()
